# GitHub Action that uses Black to reformat the Python code in an incoming pull request.
# If all Python code in the pull request is compliant with Black then this Action does nothing.
# Othewrwise, Black is run and its changes are committed back to the incoming pull request.
# https://github.com/cclauss/autoblack

name: autoblack
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: s-weigand/setup-conda@v1
      - name: Install Conda
        with:
          channels: 'conda-forge'
          python-version: '3.10'
      - run: conda --version
      - name: Install Black
        run: conda install -c conda-forge black
      - name: Run black --check .
        run: black . --exclude "external/*" --check
